-- AlterEnum
ALTER TYPE "RequestCategory" ADD VALUE 'COMMISSION';
ALTER TYPE "RequestCategory" ADD VALUE 'COST_OF_SALES';
ALTER TYPE "RequestCategory" ADD VALUE 'DEPRECIATION_AMORTIZATION';
ALTER TYPE "RequestCategory" ADD VALUE 'INTEREST_EXPENSE';
