"""drop transfer expense line item columns

Revision ID: 094711f8367c
Revises: a908233157a2
Create Date: 2026-08-31 21:47:50.276618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094711f8367c'
down_revision: Union[str, None] = 'a908233157a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfer_request_budget_source_line_item_id', table_name='transfer_request')
    op.drop_index('ix_transfer_request_expense_line_item_id', table_name='transfer_request')
    op.drop_column('transfer_request', 'expense_line_item_id')
    op.drop_column('transfer_request', 'budget_source_line_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_request', sa.Column('budget_source_line_item_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_request', sa.Column('expense_line_item_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_transfer_request_expense_line_item_id', 'transfer_request', ['expense_line_item_id'], unique=False)
    op.create_index('ix_transfer_request_budget_source_line_item_id', 'transfer_request', ['budget_source_line_item_id'], unique=False)
    # ### end Alembic commands ###
