"""npc_monitoring_io_carry_over_revised

Revision ID: 2273b7721c70
Revises: a984ace8f5fd
Create Date: 2026-09-15 15:18:06.406748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2273b7721c70'
down_revision: Union[str, None] = 'a984ace8f5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npc_monitoring_io', sa.Column('carry_over_revised_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npc_monitoring_io', 'carry_over_revised_amount')
    # ### end Alembic commands ###
