"""npc_monitoring_io_ytd_actual_by_month

Revision ID: 3fa2364fb6c4
Revises: 2273b7721c70
Create Date: 2026-09-15 15:27:22.276682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa2364fb6c4'
down_revision: Union[str, None] = '2273b7721c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npc_monitoring_io', sa.Column('ytd_actual_by_month', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npc_monitoring_io', 'ytd_actual_by_month')
    # ### end Alembic commands ###
