"""phase2 sap mock tables

Revision ID: 4c9d81ef91be
Revises: 
Create Date: 2026-08-28 13:26:49.198731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c9d81ef91be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_actual_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gl_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('item_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expense_line_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_actual_transaction_cost_center'), 'sap_actual_transaction', ['cost_center'], unique=False)
    op.create_index(op.f('ix_sap_actual_transaction_expense_line_item_id'), 'sap_actual_transaction', ['expense_line_item_id'], unique=False)
    op.create_index(op.f('ix_sap_actual_transaction_fiscal_year'), 'sap_actual_transaction', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_sap_actual_transaction_gl_account'), 'sap_actual_transaction', ['gl_account'], unique=False)
    op.create_table('sap_commitment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gl_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expense_line_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_commitment_cost_center'), 'sap_commitment', ['cost_center'], unique=False)
    op.create_index(op.f('ix_sap_commitment_expense_line_item_id'), 'sap_commitment', ['expense_line_item_id'], unique=False)
    op.create_index(op.f('ix_sap_commitment_fiscal_year'), 'sap_commitment', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_sap_commitment_gl_account'), 'sap_commitment', ['gl_account'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sap_commitment_gl_account'), table_name='sap_commitment')
    op.drop_index(op.f('ix_sap_commitment_fiscal_year'), table_name='sap_commitment')
    op.drop_index(op.f('ix_sap_commitment_expense_line_item_id'), table_name='sap_commitment')
    op.drop_index(op.f('ix_sap_commitment_cost_center'), table_name='sap_commitment')
    op.drop_table('sap_commitment')
    op.drop_index(op.f('ix_sap_actual_transaction_gl_account'), table_name='sap_actual_transaction')
    op.drop_index(op.f('ix_sap_actual_transaction_fiscal_year'), table_name='sap_actual_transaction')
    op.drop_index(op.f('ix_sap_actual_transaction_expense_line_item_id'), table_name='sap_actual_transaction')
    op.drop_index(op.f('ix_sap_actual_transaction_cost_center'), table_name='sap_actual_transaction')
    op.drop_table('sap_actual_transaction')
    # ### end Alembic commands ###
