"""note11 dash flow ticket and cost center sbu

Revision ID: 51eea702fb19
Revises: c60bcde23646
Create Date: 2026-09-08 11:46:36.486649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51eea702fb19'
down_revision: Union[str, None] = 'c60bcde23646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dash_flow_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_ticket_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_ticket_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gl_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_amount', sa.Float(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('routed_sbu', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('closed_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dash_flow_ticket_cost_center'), 'dash_flow_ticket', ['cost_center'], unique=False)
    op.create_index(op.f('ix_dash_flow_ticket_external_ticket_id'), 'dash_flow_ticket', ['external_ticket_id'], unique=True)
    op.create_index(op.f('ix_dash_flow_ticket_fiscal_year'), 'dash_flow_ticket', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_dash_flow_ticket_gl_account'), 'dash_flow_ticket', ['gl_account'], unique=False)
    op.create_index(op.f('ix_dash_flow_ticket_routed_sbu'), 'dash_flow_ticket', ['routed_sbu'], unique=False)
    op.create_index(op.f('ix_dash_flow_ticket_status'), 'dash_flow_ticket', ['status'], unique=False)
    op.add_column('cost_center', sa.Column('sbu', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_center', 'sbu')
    op.drop_index(op.f('ix_dash_flow_ticket_status'), table_name='dash_flow_ticket')
    op.drop_index(op.f('ix_dash_flow_ticket_routed_sbu'), table_name='dash_flow_ticket')
    op.drop_index(op.f('ix_dash_flow_ticket_gl_account'), table_name='dash_flow_ticket')
    op.drop_index(op.f('ix_dash_flow_ticket_fiscal_year'), table_name='dash_flow_ticket')
    op.drop_index(op.f('ix_dash_flow_ticket_external_ticket_id'), table_name='dash_flow_ticket')
    op.drop_index(op.f('ix_dash_flow_ticket_cost_center'), table_name='dash_flow_ticket')
    op.drop_table('dash_flow_ticket')
    # ### end Alembic commands ###
