"""phase4 budget report and analysis

Revision ID: 56acdaa910dc
Revises: 6440c3236e6a
Create Date: 2026-08-31 23:05:26.744257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56acdaa910dc'
down_revision: Union[str, None] = '6440c3236e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('locked_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year', 'month')
    )
    op.create_index(op.f('ix_period_lock_fiscal_year'), 'period_lock', ['fiscal_year'], unique=False)
    op.create_table('report_access_grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('granted_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_access_grant_user_id'), 'report_access_grant', ['user_id'], unique=True)
    op.create_table('report_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gl_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_note_cost_center'), 'report_note', ['cost_center'], unique=False)
    op.create_index(op.f('ix_report_note_fiscal_year'), 'report_note', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_report_note_gl_account'), 'report_note', ['gl_account'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_note_gl_account'), table_name='report_note')
    op.drop_index(op.f('ix_report_note_fiscal_year'), table_name='report_note')
    op.drop_index(op.f('ix_report_note_cost_center'), table_name='report_note')
    op.drop_table('report_note')
    op.drop_index(op.f('ix_report_access_grant_user_id'), table_name='report_access_grant')
    op.drop_table('report_access_grant')
    op.drop_index(op.f('ix_period_lock_fiscal_year'), table_name='period_lock')
    op.drop_table('period_lock')
    # ### end Alembic commands ###
