"""cc gl master lists and transfer company code

Revision ID: 6440c3236e6a
Revises: 094711f8367c
Create Date: 2026-08-31 22:13:52.655212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6440c3236e6a'
down_revision: Union[str, None] = '094711f8367c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_center_code'), 'cost_center', ['code'], unique=True)
    op.create_table('gl_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_account_code'), 'gl_account', ['code'], unique=True)
    op.add_column('transfer_request', sa.Column('company_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_request', 'company_code')
    op.drop_index(op.f('ix_gl_account_code'), table_name='gl_account')
    op.drop_table('gl_account')
    op.drop_index(op.f('ix_cost_center_code'), table_name='cost_center')
    op.drop_table('cost_center')
    # ### end Alembic commands ###
