"""phase3 transfer tables

Revision ID: 8b24ff0ffb9e
Revises: d35c1cd85ae0
Create Date: 2026-08-31 18:55:29.940244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b24ff0ffb9e'
down_revision: Union[str, None] = 'd35c1cd85ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expense_line_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_source_line_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget_source_cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget_source_gl_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sbu', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('routing_stream', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sap_document_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_request_budget_source_line_item_id'), 'transfer_request', ['budget_source_line_item_id'], unique=False)
    op.create_index(op.f('ix_transfer_request_current_stage'), 'transfer_request', ['current_stage'], unique=False)
    op.create_index(op.f('ix_transfer_request_department_id'), 'transfer_request', ['department_id'], unique=False)
    op.create_index(op.f('ix_transfer_request_expense_line_item_id'), 'transfer_request', ['expense_line_item_id'], unique=False)
    op.create_index(op.f('ix_transfer_request_fiscal_year'), 'transfer_request', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_transfer_request_requestor_id'), 'transfer_request', ['requestor_id'], unique=False)
    op.create_index(op.f('ix_transfer_request_status'), 'transfer_request', ['status'], unique=False)
    op.create_table('transfer_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_request_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transfer_request_id'], ['transfer_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_attachment_transfer_request_id'), 'transfer_attachment', ['transfer_request_id'], unique=False)
    op.create_table('transfer_review_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_request_id', sa.Integer(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decided_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transfer_request_id'], ['transfer_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_review_decision_transfer_request_id'), 'transfer_review_decision', ['transfer_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_review_decision_transfer_request_id'), table_name='transfer_review_decision')
    op.drop_table('transfer_review_decision')
    op.drop_index(op.f('ix_transfer_attachment_transfer_request_id'), table_name='transfer_attachment')
    op.drop_table('transfer_attachment')
    op.drop_index(op.f('ix_transfer_request_status'), table_name='transfer_request')
    op.drop_index(op.f('ix_transfer_request_requestor_id'), table_name='transfer_request')
    op.drop_index(op.f('ix_transfer_request_fiscal_year'), table_name='transfer_request')
    op.drop_index(op.f('ix_transfer_request_expense_line_item_id'), table_name='transfer_request')
    op.drop_index(op.f('ix_transfer_request_department_id'), table_name='transfer_request')
    op.drop_index(op.f('ix_transfer_request_current_stage'), table_name='transfer_request')
    op.drop_index(op.f('ix_transfer_request_budget_source_line_item_id'), table_name='transfer_request')
    op.drop_table('transfer_request')
    # ### end Alembic commands ###
