"""phase3 io requests and target cc-gl

Revision ID: a908233157a2
Revises: 8b24ff0ffb9e
Create Date: 2026-08-31 21:27:13.019720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a908233157a2'
down_revision: Union[str, None] = '8b24ff0ffb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_order_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('sbu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('routing_stream', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_start', sa.DateTime(), nullable=False),
    sa.Column('project_end', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_budgeted', sa.Boolean(), nullable=False),
    sa.Column('npc_budget_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reallocation_source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reallocation_npc_budget_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reallocation_io_budget_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sap_document_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_order_request_current_stage'), 'internal_order_request', ['current_stage'], unique=False)
    op.create_index(op.f('ix_internal_order_request_department_id'), 'internal_order_request', ['department_id'], unique=False)
    op.create_index(op.f('ix_internal_order_request_fiscal_year'), 'internal_order_request', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_internal_order_request_requestor_id'), 'internal_order_request', ['requestor_id'], unique=False)
    op.create_index(op.f('ix_internal_order_request_status'), 'internal_order_request', ['status'], unique=False)
    op.create_table('io_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_io_location_code'), 'io_location', ['code'], unique=True)
    op.create_table('io_review_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_order_request_id', sa.Integer(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decided_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['internal_order_request_id'], ['internal_order_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_io_review_decision_internal_order_request_id'), 'io_review_decision', ['internal_order_request_id'], unique=False)
    op.add_column('transfer_request', sa.Column('target_cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('transfer_request', sa.Column('target_gl_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('transfer_request', sa.Column('requested_classification', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_request', 'requested_classification')
    op.drop_column('transfer_request', 'target_gl_account')
    op.drop_column('transfer_request', 'target_cost_center')
    op.drop_index(op.f('ix_io_review_decision_internal_order_request_id'), table_name='io_review_decision')
    op.drop_table('io_review_decision')
    op.drop_index(op.f('ix_io_location_code'), table_name='io_location')
    op.drop_table('io_location')
    op.drop_index(op.f('ix_internal_order_request_status'), table_name='internal_order_request')
    op.drop_index(op.f('ix_internal_order_request_requestor_id'), table_name='internal_order_request')
    op.drop_index(op.f('ix_internal_order_request_fiscal_year'), table_name='internal_order_request')
    op.drop_index(op.f('ix_internal_order_request_department_id'), table_name='internal_order_request')
    op.drop_index(op.f('ix_internal_order_request_current_stage'), table_name='internal_order_request')
    op.drop_table('internal_order_request')
    # ### end Alembic commands ###
