"""npc_monitoring_import

Revision ID: a984ace8f5fd
Revises: 51eea702fb19
Create Date: 2026-09-15 09:45:21.974570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a984ace8f5fd'
down_revision: Union[str, None] = '51eea702fb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npc_monitoring_io',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('npc_sbu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aufnr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('io_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=False),
    sa.Column('committed', sa.Float(), nullable=False),
    sa.Column('allotted', sa.Float(), nullable=False),
    sa.Column('available', sa.Float(), nullable=False),
    sa.Column('source_file', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_monitoring_io_aufnr'), 'npc_monitoring_io', ['aufnr'], unique=False)
    op.create_index(op.f('ix_npc_monitoring_io_budget_code'), 'npc_monitoring_io', ['budget_code'], unique=False)
    op.create_index(op.f('ix_npc_monitoring_io_fiscal_year'), 'npc_monitoring_io', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_npc_monitoring_io_npc_sbu'), 'npc_monitoring_io', ['npc_sbu'], unique=False)
    op.create_table('npc_monitoring_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('npc_sbu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revised_amount', sa.Float(), nullable=False),
    sa.Column('source_file', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_monitoring_project_budget_code'), 'npc_monitoring_project', ['budget_code'], unique=False)
    op.create_index(op.f('ix_npc_monitoring_project_fiscal_year'), 'npc_monitoring_project', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_npc_monitoring_project_npc_sbu'), 'npc_monitoring_project', ['npc_sbu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npc_monitoring_project_npc_sbu'), table_name='npc_monitoring_project')
    op.drop_index(op.f('ix_npc_monitoring_project_fiscal_year'), table_name='npc_monitoring_project')
    op.drop_index(op.f('ix_npc_monitoring_project_budget_code'), table_name='npc_monitoring_project')
    op.drop_table('npc_monitoring_project')
    op.drop_index(op.f('ix_npc_monitoring_io_npc_sbu'), table_name='npc_monitoring_io')
    op.drop_index(op.f('ix_npc_monitoring_io_fiscal_year'), table_name='npc_monitoring_io')
    op.drop_index(op.f('ix_npc_monitoring_io_budget_code'), table_name='npc_monitoring_io')
    op.drop_index(op.f('ix_npc_monitoring_io_aufnr'), table_name='npc_monitoring_io')
    op.drop_table('npc_monitoring_io')
    # ### end Alembic commands ###
