"""report notes per expense category

Revision ID: bb53d2bd8446
Revises: 56acdaa910dc
Create Date: 2026-08-31 23:21:43.510951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb53d2bd8446'
down_revision: Union[str, None] = '56acdaa910dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Notes only existed under the old CC-GL grain up to this point (this
    # feature is brand new this session) - clearing them out rather than
    # attempting to backfill an expense_group for rows that never had one,
    # same as any other "the grain changed" migration on pre-release data.
    op.execute("DELETE FROM report_note")
    op.add_column('report_note', sa.Column('expense_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_report_note_cost_center', table_name='report_note')
    op.drop_index('ix_report_note_gl_account', table_name='report_note')
    op.create_index(op.f('ix_report_note_expense_group'), 'report_note', ['expense_group'], unique=False)
    op.drop_column('report_note', 'gl_account')
    op.drop_column('report_note', 'cost_center')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_note', sa.Column('cost_center', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('report_note', sa.Column('gl_account', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_report_note_expense_group'), table_name='report_note')
    op.create_index('ix_report_note_gl_account', 'report_note', ['gl_account'], unique=False)
    op.create_index('ix_report_note_cost_center', 'report_note', ['cost_center'], unique=False)
    op.drop_column('report_note', 'expense_group')
    # ### end Alembic commands ###
