"""sap_raw_cache

Revision ID: bd8e36267e57
Revises: 8846fbb6586f
Create Date: 2026-09-17 08:35:53.738690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd8e36267e57'
down_revision: Union[str, None] = '8846fbb6586f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_fbl3n_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gl_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('item_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_fbl3n_raw_cost_center'), 'sap_fbl3n_raw', ['cost_center'], unique=False)
    op.create_index(op.f('ix_sap_fbl3n_raw_fiscal_year'), 'sap_fbl3n_raw', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_sap_fbl3n_raw_gl_account'), 'sap_fbl3n_raw', ['gl_account'], unique=False)
    op.create_table('sap_kssb_v1_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gl_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_kssb_v1_raw_cost_center'), 'sap_kssb_v1_raw', ['cost_center'], unique=False)
    op.create_index(op.f('ix_sap_kssb_v1_raw_fiscal_year'), 'sap_kssb_v1_raw', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_sap_kssb_v1_raw_gl_account'), 'sap_kssb_v1_raw', ['gl_account'], unique=False)
    op.create_table('sap_kssb_v2_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gl_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('commitment', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_kssb_v2_raw_cost_center'), 'sap_kssb_v2_raw', ['cost_center'], unique=False)
    op.create_index(op.f('ix_sap_kssb_v2_raw_fiscal_year'), 'sap_kssb_v2_raw', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_sap_kssb_v2_raw_gl_account'), 'sap_kssb_v2_raw', ['gl_account'], unique=False)
    op.create_table('sap_salr_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aufnr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=False),
    sa.Column('committed', sa.Float(), nullable=False),
    sa.Column('allotted', sa.Float(), nullable=False),
    sa.Column('available', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_salr_raw_aufnr'), 'sap_salr_raw', ['aufnr'], unique=False)
    op.create_index(op.f('ix_sap_salr_raw_fiscal_year'), 'sap_salr_raw', ['fiscal_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sap_salr_raw_fiscal_year'), table_name='sap_salr_raw')
    op.drop_index(op.f('ix_sap_salr_raw_aufnr'), table_name='sap_salr_raw')
    op.drop_table('sap_salr_raw')
    op.drop_index(op.f('ix_sap_kssb_v2_raw_gl_account'), table_name='sap_kssb_v2_raw')
    op.drop_index(op.f('ix_sap_kssb_v2_raw_fiscal_year'), table_name='sap_kssb_v2_raw')
    op.drop_index(op.f('ix_sap_kssb_v2_raw_cost_center'), table_name='sap_kssb_v2_raw')
    op.drop_table('sap_kssb_v2_raw')
    op.drop_index(op.f('ix_sap_kssb_v1_raw_gl_account'), table_name='sap_kssb_v1_raw')
    op.drop_index(op.f('ix_sap_kssb_v1_raw_fiscal_year'), table_name='sap_kssb_v1_raw')
    op.drop_index(op.f('ix_sap_kssb_v1_raw_cost_center'), table_name='sap_kssb_v1_raw')
    op.drop_table('sap_kssb_v1_raw')
    op.drop_index(op.f('ix_sap_fbl3n_raw_gl_account'), table_name='sap_fbl3n_raw')
    op.drop_index(op.f('ix_sap_fbl3n_raw_fiscal_year'), table_name='sap_fbl3n_raw')
    op.drop_index(op.f('ix_sap_fbl3n_raw_cost_center'), table_name='sap_fbl3n_raw')
    op.drop_table('sap_fbl3n_raw')
    # ### end Alembic commands ###
