"""phase3 transfer workflow revision

Revision ID: c60bcde23646
Revises: bb53d2bd8446
Create Date: 2026-09-02 11:14:20.945114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c60bcde23646'
down_revision: Union[str, None] = 'bb53d2bd8446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # This is a structural workflow revision (DOE/GAE classification staging
    # replaced by a linear amount-gated chain - see routers/transfers.py) -
    # existing rows were created under the old stage machine and have no
    # valid mapping onto the new one (no ticket_number/sbu/location, and
    # `details` has no prior value from `reason` to carry over cleanly since
    # this table isn't append-only). These are this project's own dev/test
    # rows, not production data, so they're cleared here rather than
    # backfilled with placeholder values.
    op.execute("DELETE FROM transfer_attachment")
    op.execute("DELETE FROM transfer_review_decision")
    op.execute("DELETE FROM transfer_request")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_request', sa.Column('ticket_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('transfer_request', sa.Column('assigned_department_head_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('transfer_request', sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('transfer_request', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('transfer_request', sa.Column('stage_assignee_override_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_transfer_request_assigned_department_head_id'), 'transfer_request', ['assigned_department_head_id'], unique=False)
    op.create_index(op.f('ix_transfer_request_ticket_number'), 'transfer_request', ['ticket_number'], unique=True)
    op.drop_column('transfer_request', 'classification')
    op.drop_column('transfer_request', 'reason')
    op.drop_column('transfer_request', 'routing_stream')
    op.drop_column('transfer_request', 'requested_classification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_request', sa.Column('requested_classification', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_request', sa.Column('routing_stream', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_request', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transfer_request', sa.Column('classification', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_transfer_request_ticket_number'), table_name='transfer_request')
    op.drop_index(op.f('ix_transfer_request_assigned_department_head_id'), table_name='transfer_request')
    op.drop_column('transfer_request', 'stage_assignee_override_id')
    op.drop_column('transfer_request', 'location')
    op.drop_column('transfer_request', 'details')
    op.drop_column('transfer_request', 'assigned_department_head_id')
    op.drop_column('transfer_request', 'ticket_number')
    # ### end Alembic commands ###
