"""sap actual transaction budget code

Revision ID: d35c1cd85ae0
Revises: 4c9d81ef91be
Create Date: 2026-08-30 19:47:47.346655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd35c1cd85ae0'
down_revision: Union[str, None] = '4c9d81ef91be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sap_actual_transaction', sa.Column('budget_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_sap_actual_transaction_budget_code'), 'sap_actual_transaction', ['budget_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sap_actual_transaction_budget_code'), table_name='sap_actual_transaction')
    op.drop_column('sap_actual_transaction', 'budget_code')
    # ### end Alembic commands ###
