"""kssb_v2_plan_and_cc_department

Revision ID: e13794939450
Revises: bd8e36267e57
Create Date: 2026-09-27 00:18:47.968632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e13794939450'
down_revision: Union[str, None] = 'bd8e36267e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_center', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sap_kssb_v2_raw', sa.Column('plan', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sap_kssb_v2_raw', 'plan')
    op.drop_column('cost_center', 'department')
    # ### end Alembic commands ###
