ALTER TYPE "RequestStage" ADD VALUE 'BUDGET_OFFICER_VALIDATION';
ALTER TYPE "RequestStage" ADD VALUE 'SF_VALIDATION';
ALTER TYPE "RequestStage" ADD VALUE 'SF_HEAD_REVIEW';
ALTER TYPE "RequestStage" ADD VALUE 'SBU_HEAD_REVIEW';

ALTER TYPE "ReviewDecisionType" ADD VALUE 'REASSIGN';
ALTER TYPE "ReviewDecisionType" ADD VALUE 'CANCEL';

ALTER TABLE "BudgetRequest" ADD COLUMN "departmentHeadId" TEXT,
ADD COLUMN "sbuHeadId" TEXT,
ADD COLUMN "assigneeId" TEXT;
